version: '3.1'

services:

  back-end:
    hostname: back-end
    container_name: back-end
    build: 
      context: .
      dockerfile: back-end.Dockerfile
    image: back-end:latest
    environment:
      - TZ="Africa/Johannesburg"
    networks:
      - backend
    ports:
      - "8000:8000"

  browser-client:
    hostname: browser-client
    container_name: browser-client
    build: 
      context: ../JJClient/.
      dockerfile: ../JJClient/browser-client.Dockerfile
    image: browser-client:latest
    networks:
      - backend
    ports:
      - "80:80"
    
networks:
  backend:
    name: back-end-net
    driver: bridge

